blog/urls.py
from django.conf.urls import url
from . import views as post_views

urlpatterns = [
    url(r'^$',post_views.post_list,name='post_list'),
    # url(r'^$',post_views.PostListView.as_view(),name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        post_views.post_detail,
        name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$',
        post_views.post_share,
        name='post_share'),
    url(r'^(?P<comment_id>\d+)/comment/$',post_views.comment_reply,name='comment_reply'),
    url(r'tag/(?P<tag_slug>[-\w]+)/$',post_views.post_list,name='post_list_by_tag'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
# from mysite.blog import views as blog_views

sitemaps = {
    'posts':PostSitemap,
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # 告诉Django在blog/路径下包含了blog应用中的urls.py定义的URL模式
    url(r'blog/',include('blog.urls',
                         namespace='blog',
                         app_name='blog')),
    url(r'^sitemap\.xml$',sitemap,{'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

# url += [
#     url(r'^$',blog_views.post_list,name='post_list'),
#     url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
#         blog_views.post_detail,
#         name='post_detail'),
# ]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager  # 标签应用
# import datetime
# Create your models here.

# 创建model manage,代替Post.objects
class PublishedManager(models.Manager):
    # 原get_queryset()
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')


# # 用户
# class User(models.Model):
#     name = models.CharField()


# 帖子
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published'),
    )
    title = models.CharField(max_length=250,verbose_name='标题')
    # 设置unique_for_date,Django将不允许两个记录具有相同的slug和publish。
    # 这样就可以使用日期和帖子的slug来为所有帖子构建URL,因为他是唯一的
    slug = models.SlugField(max_length=250,unique_for_date='publish',verbose_name='标签')
    # 多对一关系(作者对帖子)
    # related_name指定User到Post的反向关系名 参考flask模型
    author = models.ForeignKey(User,related_name='blog_posts',verbose_name='作者')
    body = models.TextField(verbose_name='帖子内容')
    publish = models.DateTimeField(default=timezone.now,verbose_name='发布时间')
    created = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    updated = models.DateTimeField(auto_now=True,verbose_name='修改时间')
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft',verbose_name='状态')

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()    # 实例化标签对象

    class Meta:
        ordering = ('-publish',)   # 发布时间倒序排序
        # db_table = 'Post'           # 指定数据库生成的表名

    def __str__(self):
        return 'Post by {} on {}'.format(self.title,self.publish)   # 返回Post模型对象的title

    # 获取帖子的绝对路径 例:2017/03/11/python.html,'blog:post_detail'证明是哪个视图
    # 在模板中使用
    def get_absolute_url(self):
        return reverse('blog:post_detail',  # ?????
                       args=[self.publish.year,
                             self.publish.strftime('%m'),   # strftime格式化字符串
                             self.publish.strftime('%d'),
                             self.slug])

class Comment(models.Model):
    """
    帖子评论
    """
    post = models.ForeignKey(Post,related_name='comments',verbose_name='帖子外键')  # 外键
    name = models.CharField(max_length=80,verbose_name='姓名')
    # authors = models.ForeignKey(User,related_name='comment_user',verbose_name='评论者')
    email = models.EmailField(verbose_name='邮箱')
    body = models.TextField(verbose_name='评论内容')
    created = models.DateTimeField(auto_now_add=True,verbose_name='发表时间')
    updated = models.DateTimeField(auto_now=True,verbose_name='修改时间')
    active = models.BooleanField(default=True,verbose_name='状态')

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return '该评论由{}发表在{}文章下,作者:{}'.format(self.name,self.post,self.post.author)

    def post_name(self):
        return u'%s' % self.post.publish

    def get_author(self):
        return '{}'.format(self.post.author)

class Reply(models.Model):
#     post = models.ForeignKey(Post)
    comment = models.ForeignKey(Comment,related_name='replys',verbose_name='评论')
    name = models.CharField(max_length=80)
    to_user = models.CharField(max_length=80)
    body = models.TextField(verbose_name='内容')
    created = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    updated = models.DateTimeField(auto_now=True,verbose_name='修改时间')
    active = models.BooleanField(default=True,verbose_name='状态')
#     from_user = models.ForeignKey(User,related_name='reply_user',verbose_name='回复用户')
#     to_user = models.ForeignKey(User,verbose_name='被回复用户')
#     body = models.TextField(verbose_name='回复内容')
#     created = models.DateTimeField(auto_now_add=True,verbose_name='回复时间')
#     updated = models.DateTimeField(auto_now=True,verbose_name='修改时间')
#     active = models.BooleanField(default=True,verbose_name='状态')
#
    def __str__(self):
        return '该评论由{}回复{}'.format(self.name,self.to_user)
#
    class Meta:
        ordering = ('created',)

blog/forms.py
from django import forms
from .models import Comment,Reply

# Form表单-->邮箱
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25,label='姓名',error_messages={'required':'请输入您的称呼',
                                                                    'max_length':'称呼太长'})
    email = forms.EmailField(label='发件人邮箱',error_messages={'required':'请输入您的邮箱地址',
                                                              'invalid':'格式不正确'})
    to = forms.EmailField(label='收件人邮箱',error_messages={'required':'请输入收件人的邮箱',
                                                           'invalid':'格式不正确'})
    comments = forms.CharField(required=False,widget=forms.Textarea,label='内容')

# ModelForm表单-->评论
# 因为models里已经有评论模型,所以不需要再去重新建立一个表单
class CommentForm(forms.ModelForm):
    class Meta:
        # 声明使用Comment来构建表单,Django会解析model并动态的创建表单
        model = Comment
        # 明确指明评论表单需要用到的列
        fields = ('name','email','body')

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('name','to_user','body')

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post,Comment,Reply
from taggit.models import Tag
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm,CommentForm,ReplyForm
from django.core.mail import send_mail
from django.db.models import Count
from django.http import HttpResponsePermanentRedirect
# Create your views here.

# 基于ListView类的post_List视图
# 功能类似post_list视图
# 不是很懂

class PostListView(ListView):
    queryset = Post.published.all()         # 指定查询集合为全部Post对象
    context_object_name = 'posts'           # 环境变量posts赋给context_object_name,不指定变量则默认是object_List
    paginate_by = 2                         # 每页只显示3个对象
    template_name = 'blog/post/list.html'   # 指定模板

# 获取所有文章
def post_list(request,tag_slug=None):
    limit = 3                               # 每页显示的记录数
    object_list = Post.published.all()     # 获取所有帖子信息
    page = request.GET.get('page')  # get请求URL里面的page参数 http://abc.com/foobar?page=2 <a href="?page={{ page_number }}">
    tag = None
    if tag_slug:
        # 取出所有包含参数的标签
        tag = get_object_or_404(Tag,slug=tag_slug)
        # 过滤出包含标签的帖子
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list,limit)   # 实例化分页对象,把所有帖子按照每页3个记录显示
    try:
        posts = paginator.page(page)    # 获取某页对应的记录,如果获取到page=2 则取第二页信息
    except PageNotAnInteger:            # 如果页码不是整数
        posts = paginator.page(1)       # 取第一页记录
    except EmptyPage:                   # 如果页码太大,没有相应记录
        posts = paginator.page(paginator.num_pages)     # 则取最后一页
    return render(request,
                  'blog/post/list.html',
                  {'posts':posts,       # posts里包含所有帖子及分页后的帖子内容
                   'page':page,         # page里返回的是页面当前页数
                   'tag':tag})

def comment_reply(request,comment_id):
    comment = get_object_or_404(Comment,id=comment_id)
    replys = comment.replys.filter(active=True)
    if request.method == 'POST':
        replys_form = ReplyForm(data=request.POST)
        if replys_form.is_valid():
            new_reply = replys_form.save(commit=False)
            new_reply.comment = comment
            new_reply.save()
    else:
        replys_form = ReplyForm()
    return render(request,'blog/post/comment_reply.html',
                  {'comment':comment,
                   'replys':replys,
                   'replys_form':replys_form})

# 获取某篇文章,参数年月日
def post_detail(request,year,month,day,post):
    # 查询出相应文章
    post = get_object_or_404(Post,slug=post,
                            status='published',
                             publish__year=year)
                             # publish__month=month,    # 查询为空,如何解决?
                             # publish__day=day)
    # 查过出所有状态为True(有效)的评论的集合
    comments = post.comments.filter(active=True)
    # replys = comments.replys.filter(active=True)
    if request.method == 'POST':
        # 表单实例
        comment_form = CommentForm(data=request.POST)
        # 验证表单数据是否有效
        if comment_form.is_valid():
            # 如果save() 时commit=False，那么它将返回一个还没有保存到数据库的对象
            # 没有保存之前可以任意修改这个model对象的值
            # save()方法创建的是modelForm对象,save()方法是给modelForm对象用的而不是表单实例
            new_comment = comment_form.save(commit=False)
            # 分配一个帖子给创建的评论对象
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    # 取回包含所有tags的list集合(QuerySet),返回的是元组,使用flat=True处理他得到列表
    post_tags_ids = post.tags.values_list('id',flat=True)
    # 取回所有包含这些tags的帖子,使用exclude过滤当前id的帖子
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    # 通过聚合函数Count生成一个统计字段same_tags,包含所有需要统计标签的总数,
    # 然后对其总数进行排序,并且当不同文章拥有相同标签时,我们只取前面四篇文章
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).\
                                            order_by('-same_tags','-publish')[:4]
    return render(request,
                  'blog/post/detail.html',
                  {'post':post,
                   'comments':comments,
                   'comment_form':comment_form,
                   'similar_posts':similar_posts})
                   # 'replys':replys})

# 邮件
def post_share(request,post_id):
    post = get_object_or_404(Post,id=post_id,status='published')
    sent = False
    to = ""
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():                      # 使用is_valid方法验证提交数据是否有效
            cd = form.cleaned_data               # 将有效的数据转换为字典 {'name':'values'....}
            post_url = request.build_absolute_uri(  # 获取帖子完整的HTTP链接
                post.get_absolute_url()
            )
            # 主题
            subject = '{} ({}) recommends you reading "{}"'.\
                format(cd['name'],cd['email'],post.title)
            # 邮件内容
            message = 'Read "{}" at {} \n\n 发件人:{} \n 帖子内容:{}'.\
                format(post.title,post_url,cd['name'],cd['comments'])
            # 发送邮件(主题,内容,发件人,收件人)
            send_mail(subject,
                      message,
                      'shugaocheng@163.com',
                      [cd['to']])
            to = cd['to']
            sent = True
            # return HttpResponsePermanentRedirect('/blog/')
    else:
        form = EmailPostForm()
    return render(request,'blog/post/share.html',{'post':post,
                                                  'form':form,
                                                  'sent':sent,
                                                  'cd_to':to})

blog/templates/blog/post/comment_reply.html
{% extends "blog/base.html" %}

{% block title %}{{ comment.post }}{% endblock %}

{% block content %}
    <form action="" method="post">
        {{ replys_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="回复"></p>
    </form>
{% endblock %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        发布于: {{ post.publish }} 作者: {{ post.author }}
    </p>
{#    {{ post.body|linebreaks }}#}{{ post.body|markdown }}
    <p>
        <!---blog是命名空间,post_share:视图,post.id:参数-->
        <a href="{% url "blog:post_share" post.id %}">
            分享
        </a>
    </p>
    <h2>类似文章</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
       没有类似的文章
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }}条评论{{ total_comments|pluralize:"" }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                {# 使用forloop.counter来枚举评论,该变量包含在每次迭代的循环计数中 #}
                第{{ forloop.counter }}条评论来自{{ comment.name }} 发表于:{{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}

             <a href="{% url "blog:comment_reply" comment.id %}">
            回复
            </a>
        </div>
    {% empty %}
        <p>还没有任何评论.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>还没有任何评论.</h2>
    {% else %}
        <h2>发表评论</h2>
        <form action="" method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="评论"></p>
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My blog{% endblock %}
<!---将posts赋给pagination.html中的Page对象,--->
{% block content %}
    <h1>My blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
{#        {% if post.tags.count %}#}
{#            <p>Tags:<span class="label label-success">{{ post.tags.all|join:"," }}</span></p>#}
{#        {% endif %}#}
        <p class="date">
            发布时间: {{ post.publish }} 作者: {{ post.author }}
        </p>
{#        {{ post.body|truncatewords:30|linebreaks }}#}
        {{ post.body|markdown|truncatechars_html:30 }}
    <p class="tags">
        <span class="label label-danger">标签:</span>
        {% for tag in post.tags.all %}
            <span class="label label-info"><a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a></span>
            {% if not forloop.last %}、{% endif %}
        {% endfor %}
    </p>
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
{#    {% for error in form %}#}
{#    <div>#}
{#    {{ error.errors }}#}
{#    {{ error.label_tag }}{{ error }}#}
{#    </div>#}
{#    {% endfor %}#}
    {% if sent %}
    <h1>邮件发送成功</h1>
    <p>
    "{{ post.title }}"已成功发送到 "{{cd_to}}".
    </p>
    {% else %}
    <h1>分享 "{{ post.title }}" 的文章到邮箱</h1>
    <form action="." method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="发送" >
    </form>
    {% endif %}
{% endblock %}